apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trueberryless
  namespace: trueberryless
spec:
  secretName: trueberryless
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "trueberryless.trueberryless.org"
