apiVersion: apps/v1
kind: Deployment
metadata:
  name: trueberryless
  namespace: trueberryless
  labels:
    app: trueberryless
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trueberryless
  template:
    metadata:
      labels:
        app: trueberryless
    spec:
      containers:
        - name: trueberryless
          image: "trueberryless/trueberryless:main-7ff2cadc17386ce83d2cddbb596071e1988e8e73"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
